"""july_15

Revision ID: 515e32b25f3a
Revises: b6e707a13bb4
Create Date: 2016-07-15 16:15:00.436782

"""

# revision identifiers, used by Alembic.
revision = '515e32b25f3a'
down_revision = 'b6e707a13bb4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
