"""8/16

Revision ID: 8fe0e0ec2ea8
Revises: 4ad22f08127f
Create Date: 2016-08-16 23:44:20.663813

"""

# revision identifiers, used by Alembic.
revision = '8fe0e0ec2ea8'
down_revision = '4ad22f08127f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'ip_order_idx')
    op.add_column('interest_points', sa.Column('color', sa.Text(), nullable=True))
    op.drop_column('interest_points', 'icon')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('interest_points', 'color')
    op.add_column('images', sa.Column('ip_order_idx', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
