"""base

Revision ID: 0baa7b79af79
Revises: 1295df14fff1
Create Date: 2016-06-24 14:19:25.288863

"""

# revision identifiers, used by Alembic.
revision = '0baa7b79af79'
down_revision = '1295df14fff1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
