"""test2

Revision ID: 1295df14fff1
Revises: e84d7f546b23
Create Date: 2016-06-24 11:32:57.105354

"""

# revision identifiers, used by Alembic.
revision = '1295df14fff1'
down_revision = 'e84d7f546b23'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('test', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'test')
    ### end Alembic commands ###
