"""Test autogenerate

Revision ID: 8e04929c2203
Revises: b6e707a13bb4
Create Date: 2016-06-24 11:01:17.341352

"""

# revision identifiers, used by Alembic.
revision = '8e04929c2203'
down_revision = 'b6e707a13bb4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('taken_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'taken_at')
    ### end Alembic commands ###
